INSERT INTO `rooms` (`name`, `label`, `order`) VALUES
('living_room', 'Living Room', 100),
('dining_room', 'Dining Room', 200),
('kitchen', 'Kitchen', 300),
('hallway', 'Hallway', 400),
('matts_office', 'Matt''s Office', 500),
('ashlees_office', 'Ashlee''s Office', 600),
('master_bedroom', 'Master Bedroom', 700),
('vanity', 'Vanity', 800),
('master_bathroom', 'Master Bathroom', 900),
('closet', 'Closet', 1000);


INSERT INTO `groups` (`name`, `label`, `order`) VALUES
('living_room', 'Living Room', 100),
('tv_roku', 'TV/Roku', 150),
('dining_chandelier', 'Dining Chandelier', 200),
('kitchen', 'Kitchen', 300),
('kitchen_hanging', 'Kitchen Hanging', 333),
('kitchen_main', 'Kitchen Main', 367),
('hall', 'Hall', 400),
('matts_office', 'Matt''s Office', 500),
('office_smart_socket', 'Office Smart Socket', 550),
('ashlees_office', 'Ashlee''s Office', 600),
('office', 'Office', 620),
('office_1', 'Office 1', 640),
('office_2', 'Office 2', 660),
('office_3', 'Office 3', 680),
('master_bedroom', 'Master Bedroom', 700),
('matts_phone_charger', 'Matt''s Phone Charger', 733),
('candle', 'Candle', 767),
('master_vanity', 'Master Vanity', 800),
('master_bath', 'Master Bath', 900),
('closet', 'Closet', 1000),
('matts_usb_charger', 'Matt''s USB Charger', 2000);


INSERT INTO `devices` (`mfg_id`, `room_id`, `name`, `label`, `platform`, `type`, `order`) VALUES
('1909208099330390802548e1e952724b', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'living_room_1', 'Living Room 1', 'meross', 'bulb', 100),
('1909209106213290802548e1e9527673', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'living_room_2', 'Living Room 2', 'meross', 'bulb', 117),
('1909206601158890802548e1e952803f', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'living_room_3', 'Living Room 3', 'meross', 'bulb', 133),
('1909205690321990802548e1e95272c3', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'living_room_4', 'Living Room 4', 'meross', 'bulb', 150),
('10021424b4e62d5b0676_1', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'tv', 'TV', 'tuya', 'socket', 167),
('10021424b4e62d5b0676_7', (SELECT `id` FROM `rooms` WHERE `name` = 'living_room'), 'roku', 'Roku', 'tuya', 'socket', 184),
('1909201173069090802548e1e9527d71', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'dining_chandelier_1', 'Dining Chandelier 1', 'meross', 'bulb', 200),
('1909209351276590802548e1e9526d54', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'dining_chandelier_2', 'Dining Chandelier 2', 'meross', 'bulb', 220),
('1909201157767590802548e1e95281ec', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'dining_chandelier_3', 'Dining Chandelier 3', 'meross', 'bulb', 240),
('1909203866252390802548e1e9527008', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'dining_chandelier_4', 'Dining Chandelier 4', 'meross', 'bulb', 260),
('1909203726704190802548e1e9526c6b', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'dining_chandelier_5', 'Dining Chandelier 5', 'meross', 'bulb', 280),
('1909207339091590802548e1e952717b', (SELECT `id` FROM `rooms` WHERE `name` = 'kitchen'), 'kitchen_1', 'Kitchen 1', 'meross', 'bulb', 300),
('1909209187918890802548e1e95269a7', (SELECT `id` FROM `rooms` WHERE `name` = 'kitchen'), 'kitchen_2', 'Kitchen 2', 'meross', 'bulb', 320),
('1909208906307090802548e1e95266a8', (SELECT `id` FROM `rooms` WHERE `name` = 'kitchen'), 'kitchen_3', 'Kitchen 3', 'meross', 'bulb', 340),
('1909204444070390802548e1e952664e', (SELECT `id` FROM `rooms` WHERE `name` = 'kitchen'), 'kitchen_hanging_1', 'Kitchen Hanging 1', 'meross', 'bulb', 360),
('1909204332519190802548e1e95282bb', (SELECT `id` FROM `rooms` WHERE `name` = 'kitchen'), 'kitchen_hanging_2', 'Kitchen Hanging 2', 'meross', 'bulb', 380),
('1909209011876790802548e1e952689d', (SELECT `id` FROM `rooms` WHERE `name` = 'hallway'), 'hall_1', 'Hall 1', 'meross', 'bulb', 400),
('1909206181490590802548e1e9527bd2', (SELECT `id` FROM `rooms` WHERE `name` = 'hallway'), 'hall_2', 'Hall 2', 'meross', 'bulb', 425),
('1909200779268290802548e1e9527bdb', (SELECT `id` FROM `rooms` WHERE `name` = 'hallway'), 'hall_3', 'Hall 3', 'meross', 'bulb', 450),
('1909205384940990802548e1e952726a', (SELECT `id` FROM `rooms` WHERE `name` = 'hallway'), 'hall_4', 'Hall 4', 'meross', 'bulb', 475),
('1909204138839390802548e1e9526d83', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'matts_office_1', 'Matt''s Office 1', 'meross', 'bulb', 500),
('1909209096522490802548e1e9527eaa', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'matts_office_2', 'Matt''s Office 2', 'meross', 'bulb', 520),
('1909205060573590802548e1e9527aaf', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'matts_office_3', 'Matt''s Office 3', 'meross', 'bulb', 540),
('10021424ecfabc29d946_1', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'nargothrond', 'Nargothrond', 'tuya', 'socket', 560),
('10021424ecfabc29d946_7', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'matts_usb_charger_office', 'Matt''s USB Charger (office)', 'tuya', 'socket', 580),
('1909202461469090802548e1e95275d8', (SELECT `id` FROM `rooms` WHERE `name` = 'ashlees_office'), 'ashlees_office_1', 'Ashlee''s Office 1', 'meross', 'bulb', 600),
('1909208074936090802548e1e952713a', (SELECT `id` FROM `rooms` WHERE `name` = 'ashlees_office'), 'ashlees_office_2', 'Ashlee''s Office 2', 'meross', 'bulb', 633),
('1909204889052390802548e1e95267e1', (SELECT `id` FROM `rooms` WHERE `name` = 'ashlees_office'), 'ashlees_office_3', 'Ashlee''s Office 3', 'meross', 'bulb', 667),
('1909203216975990802548e1e9527050', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'master_bedroom_1', 'Master Bedroom 1', 'meross', 'bulb', 700),
('1909207153246790802548e1e95281ed', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'master_bedroom_2', 'Master Bedroom 2', 'meross', 'bulb', 717),
('1909204719826890802548e1e9526cbc', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'master_bedroom_3', 'Master Bedroom 3', 'meross', 'bulb', 733),
('1909207713761790802548e1e95272d5', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'bedroom_lamp', 'Bedroom lamp', 'meross', 'bulb', 750),
('10021424b4e62d5b11b4_1', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'matts_charger_socket', 'Matt''s Charger Socket', 'tuya', 'socket', 767),
('10021424b4e62d5b11b4_7', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bedroom'), 'matts_usb_charger_bedroom', 'Matt''s USB Charger (bedroom)', 'tuya', 'socket', 784),
('1909201385910590802548e1e952771b', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'master_vanity_1', 'Master Vanity 1', 'meross', 'bulb', 800),
('1909204971291490802548e1e95265f0', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'master_vanity_2', 'Master Vanity 2', 'meross', 'bulb', 817),
('1909207580032190802548e1e95284ad', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'master_vanity_3', 'Master Vanity 3', 'meross', 'bulb', 833),
('1909207860645390802548e1e9526a5e', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'master_vanity_4', 'Master Vanity 4', 'meross', 'bulb', 850),
('10021424b4e62d5b016d_1', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'candle_socket', 'Candle Socket', 'tuya', 'socket', 867),
('10021424b4e62d5b016d_7', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'vanity_usb', 'Vanity USB', 'tuya', 'socket', 884),
('1909205143912290802548e1e9526e05', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bathroom'), 'master_bath_1', 'Master Bath 1', 'meross', 'bulb', 900),
('1909201427743090802548e1e952764b', (SELECT `id` FROM `rooms` WHERE `name` = 'master_bathroom'), 'master_bath_2', 'Master Bath 2', 'meross', 'bulb', 950),
('1909209533875690802548e1e952687f', (SELECT `id` FROM `rooms` WHERE `name` = 'closet'), 'closet_1', 'Closet 1', 'meross', 'bulb', 1000),
('1909202315369590802548e1e95266a9', (SELECT `id` FROM `rooms` WHERE `name` = 'closet'), 'closet_2', 'Closet 2', 'meross', 'bulb', 1050);


INSERT INTO `groups_models` (`group_id`, `model`, `model_id`) VALUES
((SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_1'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_1'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_2'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_2'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_3'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'ashlees_office_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_3'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'kitchen_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'kitchen_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'kitchen_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'kitchen_hanging_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'kitchen_hanging_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_4')),
((SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'closet_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'closet_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_4')),
((SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'living_room_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'living_room_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'living_room_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'living_room_4')),
((SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_1')),
((SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_2')),
((SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_3')),
((SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_4')),
((SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_5')),
((SELECT `id` FROM `groups` WHERE `name` = 'candle'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'candle_socket')),
((SELECT `id` FROM `groups` WHERE `name` = 'candle'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'vanity_usb')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_smart_socket'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'nargothrond')),
((SELECT `id` FROM `groups` WHERE `name` = 'office_smart_socket'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_usb_charger_office')),
((SELECT `id` FROM `groups` WHERE `name` = 'tv_roku'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'tv')),
((SELECT `id` FROM `groups` WHERE `name` = 'tv_roku'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'roku')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_phone_charger'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_charger_socket')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_phone_charger'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_usb_charger_bedroom')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_usb_charger'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_usb_charger_office')),
((SELECT `id` FROM `groups` WHERE `name` = 'matts_usb_charger'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_usb_charger_bedroom')),
((SELECT `id` FROM `groups` WHERE `name` = 'office'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office')),
((SELECT `id` FROM `groups` WHERE `name` = 'office'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main')),
((SELECT `id` FROM `groups` WHERE `name` = 'kitchen'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'));


INSERT INTO `presets` (`model`, `model_id`, `name`, `label`) VALUES
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'good_morning', 'Good Morning'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'bedtime', 'Bedtime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'nightlight', 'Nightlight'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'bedtime', 'Bedtime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'daytime', 'Daytime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'evening', 'Evening'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'bedtime', 'Bedtime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'nightlight', 'Nightlight'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'movie', 'Movie'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'movie', 'Movie'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'movie', 'Movie'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'bedtime', 'Bedtime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_1'), 'nightlight', 'Nightlight'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_3'), 'nightlight', 'Nightlight'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'good_morning', 'Good Morning'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'bedtime', 'Bedtime'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2'), 'nightlight', 'Nightlight'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'daytime', 'Daytime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'evening', 'Evening'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'movie', 'Movie'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'bedtime', 'Bedtime'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'daytime', 'Daytime'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'evening', 'Evening'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'movie', 'Movie'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), 'bedtime', 'Bedtime'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'tv_roku'), 'movie', 'Movie');


INSERT INTO `preset_actions` (`preset_id`, `action`, `value`, `datatype`) VALUES
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 56, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'good_morning'), 'brightness', 50, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'good_morning'), 'temperature', 56, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 37, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'bedtime'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'bedtime'), 'temperature', 37, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1') AND `model` = 'device' AND `name` = 'nightlight'), 'brightness', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1') AND `model` = 'device' AND `name` = 'nightlight'), 'color', 'redorange', 'string'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 67, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 65, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 33, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'daytime'), 'brightness', 50, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'daytime'), 'temperature', 55, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'evening'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'evening'), 'temperature', 23, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'bedtime'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'bedtime'), 'temperature', 23, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'nightlight'), 'brightness', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'nightlight'), 'color', 'redorange', 'string'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 39, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 8, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 39, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 39, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 8, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 39, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 31, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 15, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 26, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'movie'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 31, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 5, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'movie'), 'brightness', 5, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'movie'), 'temperature', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 50, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 15, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 25, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'movie'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'hall_1') AND `model` = 'device' AND `name` = 'nightlight'), 'brightness', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'hall_1') AND `model` = 'device' AND `name` = 'nightlight'), 'color', 'redorange', 'string'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'hall_3') AND `model` = 'device' AND `name` = 'nightlight'), 'brightness', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'hall_3') AND `model` = 'device' AND `name` = 'nightlight'), 'color', 'redorange', 'string'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 100, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 65, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 12, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 39, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 51, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'good_morning'), 'brightness', 18, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'good_morning'), 'temperature', 33, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 15, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'bedtime'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'bedtime'), 'temperature', 15, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2') AND `model` = 'device' AND `name` = 'nightlight'), 'brightness', 1, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2') AND `model` = 'device' AND `name` = 'nightlight'), 'color', 'redorange', 'string'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'daytime'), 'brightness', 75, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'daytime'), 'temperature', 33, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'evening'), 'brightness', 7, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'evening'), 'temperature', 24, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'movie'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'daytime'), 'brightness', 66, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'daytime'), 'temperature', 24, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'evening'), 'brightness', 10, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'evening'), 'temperature', 24, 'number'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'movie'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'bedtime'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'tv_roku') AND `model` = 'group' AND `name` = 'movie'), 'on', TRUE, 'boolean');


INSERT INTO `conditional_actions` (`model`, `model_id`, `preset_id`, `action`, `condition_type`, `condition`) VALUES
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bath') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'daytime'), 'on', 'time', NULL),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp') AND `model` = 'device' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'matts_office') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'hall') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'closet') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'daytime'), 'on', 'time', NULL),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `groups` WHERE `name` = 'living_room') AND `model` = 'group' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'daytime'), 'on', 'time', NULL),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room'), (SELECT `id` FROM `presets` WHERE `model_id` = (SELECT `id` FROM `rooms` WHERE `name` = 'dining_room') AND `model` = 'room' AND `name` = 'evening'), 'on', 'time', 'sunset-1h->sunrise');


INSERT INTO `aliases` (`model`, `model_id`, `alias`, `label`) VALUES
('device', (SELECT `id` FROM `devices` WHERE `name` = 'candle_socket'), 'air_freshener', 'Air Freshener'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'candle_socket'), 'fan', 'Fan'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'candle_socket'), 'bedroom_fan', 'Bedroom Fan'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'candle_socket'), 'master_bedroom_fan', 'Master Bedroom Fan'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'nargothrond'), 'computer', 'Computer'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'nargothrond'), 'plex', 'Plex'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'master_bathroom', 'Master Bathroom'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'master_bathroom_1', 'Master Bathroom 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'master_bathroom_2', 'Master Bathroom 2'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'bathroom', 'Bathroom'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'bathroom_1', 'Bathroom 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'bathroom_2', 'Bathroom 2'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'bedroom', 'Bedroom'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_1'), 'bedroom_1', 'Bedroom 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_2'), 'bedroom_2', 'Bedroom 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bedroom_3'), 'bedroom_3', 'Bedroom 3'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'master_bedroom_lamp', 'Master Bedroom Lamp'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'guest_room', 'Guest Room'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'guest_room', 'Guest Room'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_1'), 'guest_room_1', 'Guest Room 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_2'), 'guest_room_2', 'Guest Room 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_3'), 'guest_room_3', 'Guest Room 3'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'matts_office'), 'guest_bedroom', 'Guest Bedroom'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'guest_bedroom', 'Guest Bedroom'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_1'), 'guest_bedroom_1', 'Guest Bedroom 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_2'), 'guest_bedroom_2', 'Guest Bedroom 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'matts_office_3'), 'guest_bedroom_3', 'Guest Bedroom 3'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'hallway'), 'hall', 'Hall'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'hallway', 'Hallway'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_1'), 'hallway_1', 'Hallway 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_2'), 'hallway_2', 'Hallway 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_3'), 'hallway_3', 'Hallway 3'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_4'), 'hallway_4', 'Hallway 4'),
('room', (SELECT `id` FROM `rooms` WHERE `name` = 'vanity'), 'master_vanity', 'Master Vanity'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'vanity', 'Vanity'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_1'), 'vanity_1', 'Vanity 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2'), 'vanity_2', 'Vanity 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_3'), 'vanity_3', 'Vanity 3'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_4'), 'vanity_4', 'Vanity 4'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'dining_room', 'Dining Room'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_1'), 'dining_room_1', 'Dining Room 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_2'), 'dining_room_2', 'Dining Room 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_3'), 'dining_room_3', 'Dining Room 3'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_4'), 'dining_room_4', 'Dining Room 4'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_5'), 'dining_room_5', 'Dining Room 5'),
('group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'chandelier', 'Chandelier'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_1'), 'chandelier_1', 'Chandelier 1'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_2'), 'chandelier_2', 'Chandelier 2'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_3'), 'chandelier_3', 'Chandelier 3'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_4'), 'chandelier_4', 'Chandelier 4'),
('device', (SELECT `id` FROM `devices` WHERE `name` = 'dining_chandelier_5'), 'chandelier_5', 'Chandelier 5');


INSERT INTO `scenes` (`name`, `label`, `order`) VALUES
('daytime_all', 'Daytime All', 100),
('good_morning', 'Good Morning', 200),
('evening_all', 'Evening All', 300),
('evening', 'Evening', 400),
('movie', 'Movie', 500),
('bedtime', 'Bedtime', 600),
('nightlight', 'Nightlight', 700);


INSERT INTO `scene_actions` (`scene_id`, `model`, `model_id`, `action`, `value`, `datatype`) VALUES
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'daytime_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'preset', 'daytime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'good_morning'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'preset', 'good_morning', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'good_morning'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'preset', 'good_morning', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening_all'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'evening'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'preset', 'evening', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'tv_roku'), 'preset', 'movie', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'preset', 'movie', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'preset', 'movie', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_main'), 'preset', 'movie', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'movie'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen_hanging'), 'preset', 'movie', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'dining_chandelier'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'living_room'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_vanity'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'closet'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'hall'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'kitchen'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'matts_office'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'ashlees_office'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bedroom'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'bedtime'), 'group', (SELECT `id` FROM `groups` WHERE `name` = 'master_bath'), 'preset', 'bedtime', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'nightlight'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_1'), 'preset', 'nightlight', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'nightlight'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'hall_3'), 'preset', 'nightlight', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'nightlight'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'bedroom_lamp'), 'off', TRUE, 'boolean'),
((SELECT `id` FROM `scenes` WHERE `name` = 'nightlight'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_bath_1'), 'preset', 'nightlight', 'string'),
((SELECT `id` FROM `scenes` WHERE `name` = 'nightlight'), 'device', (SELECT `id` FROM `devices` WHERE `name` = 'master_vanity_2'), 'preset', 'nightlight', 'string');


INSERT INTO `colors` (`name`, `label`, `value`, `display_value`) VALUES ('redorange', 'Red Orange', '#ff6201', '#ff6201');
