INSERT INTO smart_home.rooms (name,label,`order`,active) VALUES
	 ('living_room','Living Room',100,1),
	 ('dining_room','Dining Room',200,1),
	 ('kitchen','Kitchen',300,1),
	 ('hallway','Hallway',400,1),
	 ('office','Office',500,1),
	 ('kids_room','Kids'' Room',600,1),
	 ('bedroom','Bedroom',700,1),
	 ('vanity','Vanity',800,1),
	 ('bathroom','Bathroom',900,1),
	 ('closet','Closet',1000,1),
	 ('bedroom_lamp','Bedroom Lamp',750,1),
	 ('balcony','Balcony',1100,1),
	 ('christmas_tree','Christmas Tree',33,1),
	 ('ship','Ship',50,1),
	 ('matts_usb_charger','Matt''s USB Charger',2147483647,1);

INSERT INTO smart_home.devices (mfg_id,room_id,name,label,platform,`type`,mfg_model,mfg_sub_model,firmware_version,hardware_version,`order`,active) VALUES
	 ('1909208099330390802548e1e952724b',(SELECT id FROM rooms WHERE name = 'living_room'),'living_room_1','Living Room 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',100,1),
	 ('1909209106213290802548e1e9527673',(SELECT id FROM rooms WHERE name = 'living_room'),'living_room_2','Living Room 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',110,1),
	 ('1909206601158890802548e1e952803f',(SELECT id FROM rooms WHERE name = 'living_room'),'living_room_3','Living Room 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',120,1),
	 ('1909205690321990802548e1e95272c3',(SELECT id FROM rooms WHERE name = 'living_room'),'living_room_4','Living Room 4','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',130,1),
	 ('10021424b4e62d5b0676_1',(SELECT id FROM rooms WHERE name = 'office'),'office_power_strip','Office Power Strip','tuya','socket','sp25',NULL,'1.0.0','1.0.0',140,1),
	 ('10021424b4e62d5b0676_7',(SELECT id FROM rooms WHERE name = 'office'),'office_usb','Office USB','tuya','socket','sp25',NULL,'1.0.0','1.0.0',150,1),
	 ('1909209875999590802548e1e952681d',(SELECT id FROM rooms WHERE name = 'dining_room'),'dining_room_1','Dining Room 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',200,1),
	 ('1909209351276590802548e1e9526d54',(SELECT id FROM rooms WHERE name = 'dining_room'),'dining_room_2','Dining Room 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',210,1),
	 ('1909201157767590802548e1e95281ec',(SELECT id FROM rooms WHERE name = 'dining_room'),'dining_room_3','Dining Room 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',220,1),
	 ('1909203866252390802548e1e9527008',(SELECT id FROM rooms WHERE name = 'dining_room'),'dining_room_4','Dining Room 4','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',230,1),
	 ('1909203726704190802548e1e9526c6b',(SELECT id FROM rooms WHERE name = 'dining_room'),'dining_room_5','Dining Room 5','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',240,1),
	 ('1909206181490590802548e1e9527bd2',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_1','Kitchen 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',300,1),
	 ('2004175188477690810748e1e91a0530',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_2','Kitchen 2','meross_local','bulb','msl120','msl120d','2.1.16','2.0.0',310,1),
	 ('1909205384940990802548e1e952726a',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_3','Kitchen 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',320,1),
	 ('1909204444070390802548e1e952664e',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_hanging_1','Kitchen Hanging 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',330,1),
	 ('1909204332519190802548e1e95282bb',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_hanging_2','Kitchen Hanging 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',340,1),
	 ('1909209011876790802548e1e952689d',(SELECT id FROM rooms WHERE name = 'hallway'),'hall_1','Hall 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',400,1),
	 ('1909207339091590802548e1e952717b',(SELECT id FROM rooms WHERE name = 'hallway'),'hall_2','Hall 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',410,0),
	 ('1909200779268290802548e1e9527bdb',(SELECT id FROM rooms WHERE name = 'hallway'),'hall_3','Hall 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',420,1),
	 ('1909208906307090802548e1e95266a8',(SELECT id FROM rooms WHERE name = 'hallway'),'hall_4','Hall 4','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',430,0),
	 ('1909204138839390802548e1e9526d83',(SELECT id FROM rooms WHERE name = 'office'),'office_1','Office 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',500,1),
	 ('1909209096522490802548e1e9527eaa',(SELECT id FROM rooms WHERE name = 'office'),'office_2','Office 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',510,1),
	 ('1909205060573590802548e1e9527aaf',(SELECT id FROM rooms WHERE name = 'office'),'office_3','Office 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',520,1),
	 ('10021424ecfabc29d946_1',(SELECT id FROM rooms WHERE name = 'christmas_tree'),'christmas_tree','Christmas Tree','tuya','bulb','sp25',NULL,'1.0.0','1.0.0',530,1),
	 ('10021424ecfabc29d946_7',(SELECT id FROM rooms WHERE name = 'christmas_tree'),'christmas_tree_usb','Christmas Tree USB','tuya','socket','sp25',NULL,'1.0.0','1.0.0',540,1),
	 ('1909202461469090802548e1e95275d8',(SELECT id FROM rooms WHERE name = 'kids_room'),'kids_room_1','Kids'' Room 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',600,1),
	 ('1909208074936090802548e1e952713a',(SELECT id FROM rooms WHERE name = 'kids_room'),'kids_room_2','Kids'' Room 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',610,1),
	 ('1909204889052390802548e1e95267e1',(SELECT id FROM rooms WHERE name = 'kids_room'),'kids_room_3','Kids'' Room 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',620,1),
	 ('1909203216975990802548e1e9527050',(SELECT id FROM rooms WHERE name = 'bedroom'),'bedroom_1','Bedroom 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',700,1),
	 ('1909207153246790802548e1e95281ed',(SELECT id FROM rooms WHERE name = 'bedroom'),'bedroom_2','Bedroom 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',710,1),
	 ('1909204719826890802548e1e9526cbc',(SELECT id FROM rooms WHERE name = 'bedroom'),'bedroom_3','Bedroom 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',720,1),
	 ('1909207713761790802548e1e95272d5',(SELECT id FROM rooms WHERE name = 'bedroom_lamp'),'bedroom_lamp','Bedroom lamp','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',730,1),
	 ('10021424b4e62d5b11b4_1',(SELECT id FROM rooms WHERE name = 'bedroom'),'matts_charger_socket','Matt''s Charger Socket','tuya','socket','sp25',NULL,'1.0.0','1.0.0',740,1),
	 ('10021424b4e62d5b11b4_7',(SELECT id FROM rooms WHERE name = 'matts_usb_charger'),'matts_usb_charger_bedroom','Matt''s USB Charger (bedroom)','tuya','socket','sp25',NULL,'1.0.0','1.0.0',750,1),
	 ('1909204734378290802548e1e9526d76',(SELECT id FROM rooms WHERE name = 'vanity'),'vanity_1','Vanity 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',800,0),
	 ('1909204971291490802548e1e95265f0',(SELECT id FROM rooms WHERE name = 'vanity'),'vanity_2','Vanity 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',810,1),
	 ('1909207580032190802548e1e95284ad',(SELECT id FROM rooms WHERE name = 'vanity'),'vanity_3','Vanity 3','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',820,1),
	 ('1909207860645390802548e1e9526a5e',(SELECT id FROM rooms WHERE name = 'vanity'),'vanity_4','Vanity 4','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',830,1),
	 ('10021424b4e62d5b016d_1',(SELECT id FROM rooms WHERE name = 'ship'),'ship','Ship','tuya','bulb','sp25',NULL,'1.0.0','1.0.0',880,1),
	 ('10021424b4e62d5b016d_7',(SELECT id FROM rooms WHERE name = 'ship'),'ship_usb','Ship USB','tuya','socket','sp25',NULL,'1.0.0','1.0.0',890,1),
	 ('1909205143912290802548e1e9526e05',(SELECT id FROM rooms WHERE name = 'bathroom'),'bathroom_1','Bathroom 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',900,1),
	 ('1909201427743090802548e1e952764b',(SELECT id FROM rooms WHERE name = 'bathroom'),'bathroom_2','Bathroom 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',910,1),
	 ('1909209533875690802548e1e952687f',(SELECT id FROM rooms WHERE name = 'closet'),'closet_1','Closet 1','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',1000,1),
	 ('1909202315369590802548e1e95266a9',(SELECT id FROM rooms WHERE name = 'closet'),'closet_2','Closet 2','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',1010,1),
	 ('1909209187918890802548e1e95269a7',(SELECT id FROM rooms WHERE name = 'balcony'),'balcony','Balcony','meross_local','bulb','msl120','msl120b','2.1.16','2.0.0',2147483647,1),
	 ('C013CD',(SELECT id FROM rooms WHERE name = 'office'),'office_light_switch_old','Office Light Switch (Old)','tasmota','dimmer','Gosund_SW2','Gosund_SW2','12.0.2_GS1.2','2',5000,0),
	 ('2203082275712525587248e1e98bb0a8',(SELECT id FROM rooms WHERE name = 'bathroom'),'bathroom_light_switch','Bathroom Light Switch','meross_local','dimmer','mss560','mss560x','3.1.9','3.0.0',920,1),
	 ('2203082560994425587248e1e98bb34c',(SELECT id FROM rooms WHERE name = 'vanity'),'vanity_light_switch','Vanity Light Switch','meross_local','dimmer','mss560','mss560x','3.1.9','3.0.0',840,1),
	 ('2203088461932025587248e1e98bab26',(SELECT id FROM rooms WHERE name = 'kitchen'),'kitchen_light_switch','Kitchen Light Switch','meross_local','dimmer','mss560','mss560x','3.1.9','3.0.0',350,1),
	 ('2203080384475125587248e1e98bb374',(SELECT id FROM rooms WHERE name = 'office'),'office_light_switch','Office Light Switch','meross_local','dimmer','mss560','mss560x','3.1.9','3.0.0',550,1),
	 ('2203085259877825587248e1e98bab8f',(SELECT id FROM rooms WHERE name = 'kids_room'),'kids_room_light_switch','Kids'' Room Light Switch','meross_local','dimmer','mss560','mss560x','3.1.9','3.0.0',630,1);

INSERT INTO smart_home.groups (name,label,`order`,active) VALUES
	 ('living_room','Living Room',100,1),
	 ('tv_roku','TV/Roku',150,1),
	 ('dining_chandelier','Dining Chandelier',200,1),
	 ('kitchen','Kitchen',300,1),
	 ('kitchen_hanging','Kitchen Hanging',333,1),
	 ('kitchen_main','Kitchen Main',367,1),
	 ('hall','Hall',400,1),
	 ('kids_room','Kids'' Room',600,1),
	 ('office','Office',620,1),
	 ('bedroom','Bedroom',700,1),
	 ('matts_phone_charger','Matt''s Phone Charger',733,1),
	 ('living_room_socket','Living Room Socket',767,1),
	 ('vanity','Vanity',800,1),
	 ('bathroom','Bathroom',900,1),
	 ('closet','Closet',1000,1),
	 ('matts_usb_charger','Matt''s USB Charger',2000,1);

INSERT INTO smart_home.groups_models (group_id,model,model_id,active) VALUES
	 ((SELECT id FROM groups WHERE name = 'bathroom'),'device',(SELECT id FROM devices WHERE name = 'bathroom_1'),1),
	 ((SELECT id FROM groups WHERE name = 'bathroom'),'device',(SELECT id FROM devices WHERE name = 'bathroom_2'),1),
	 ((SELECT id FROM groups WHERE name = 'bedroom'),'device',(SELECT id FROM devices WHERE name = 'bedroom_1'),1),
	 ((SELECT id FROM groups WHERE name = 'bedroom'),'device',(SELECT id FROM devices WHERE name = 'bedroom_2'),1),
	 ((SELECT id FROM groups WHERE name = 'bedroom'),'device',(SELECT id FROM devices WHERE name = 'bedroom_3'),1),
	 ((SELECT id FROM groups WHERE name = 'office'),'device',(SELECT id FROM devices WHERE name = 'office_1'),1),
	 ((SELECT id FROM groups WHERE name = 'office'),'device',(SELECT id FROM devices WHERE name = 'office_2'),1),
	 ((SELECT id FROM groups WHERE name = 'office'),'device',(SELECT id FROM devices WHERE name = 'office_3'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen_main'),'device',(SELECT id FROM devices WHERE name = 'kitchen_1'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen_main'),'device',(SELECT id FROM devices WHERE name = 'kitchen_2'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen_main'),'device',(SELECT id FROM devices WHERE name = 'kitchen_3'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen_hanging'),'device',(SELECT id FROM devices WHERE name = 'kitchen_hanging_1'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen_hanging'),'device',(SELECT id FROM devices WHERE name = 'kitchen_hanging_2'),1),
	 ((SELECT id FROM groups WHERE name = 'hall'),'device',(SELECT id FROM devices WHERE name = 'hall_1'),1),
	 ((SELECT id FROM groups WHERE name = 'hall'),'device',(SELECT id FROM devices WHERE name = 'hall_2'),1),
	 ((SELECT id FROM groups WHERE name = 'hall'),'device',(SELECT id FROM devices WHERE name = 'hall_3'),1),
	 ((SELECT id FROM groups WHERE name = 'hall'),'device',(SELECT id FROM devices WHERE name = 'hall_4'),1),
	 ((SELECT id FROM groups WHERE name = 'closet'),'device',(SELECT id FROM devices WHERE name = 'closet_1'),1),
	 ((SELECT id FROM groups WHERE name = 'closet'),'device',(SELECT id FROM devices WHERE name = 'closet_2'),1),
	 ((SELECT id FROM groups WHERE name = 'vanity'),'device',(SELECT id FROM devices WHERE name = 'vanity_1'),1),
	 ((SELECT id FROM groups WHERE name = 'vanity'),'device',(SELECT id FROM devices WHERE name = 'vanity_2'),1),
	 ((SELECT id FROM groups WHERE name = 'vanity'),'device',(SELECT id FROM devices WHERE name = 'vanity_3'),1),
	 ((SELECT id FROM groups WHERE name = 'vanity'),'device',(SELECT id FROM devices WHERE name = 'vanity_4'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room'),'device',(SELECT id FROM devices WHERE name = 'living_room_1'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room'),'device',(SELECT id FROM devices WHERE name = 'living_room_2'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room'),'device',(SELECT id FROM devices WHERE name = 'living_room_3'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room'),'device',(SELECT id FROM devices WHERE name = 'living_room_4'),1),
	 ((SELECT id FROM groups WHERE name = 'dining_chandelier'),'device',(SELECT id FROM devices WHERE name = 'dining_room_1'),1),
	 ((SELECT id FROM groups WHERE name = 'dining_chandelier'),'device',(SELECT id FROM devices WHERE name = 'dining_room_2'),1),
	 ((SELECT id FROM groups WHERE name = 'dining_chandelier'),'device',(SELECT id FROM devices WHERE name = 'dining_room_3'),1),
	 ((SELECT id FROM groups WHERE name = 'dining_chandelier'),'device',(SELECT id FROM devices WHERE name = 'dining_room_4'),1),
	 ((SELECT id FROM groups WHERE name = 'dining_chandelier'),'device',(SELECT id FROM devices WHERE name = 'dining_room_5'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room_socket'),'device',(SELECT id FROM devices WHERE name = 'ship'),1),
	 ((SELECT id FROM groups WHERE name = 'living_room_socket'),'device',(SELECT id FROM devices WHERE name = 'ship_usb'),1),
	 ((SELECT id FROM groups WHERE name = 'office'),'device',(SELECT id FROM devices WHERE name = 'office_power_strip'),1),
	 ((SELECT id FROM groups WHERE name = 'office'),'device',(SELECT id FROM devices WHERE name = 'office_usb'),1),
	 ((SELECT id FROM groups WHERE name = 'matts_phone_charger'),'device',(SELECT id FROM devices WHERE name = 'matts_charger_socket'),1),
	 ((SELECT id FROM groups WHERE name = 'matts_phone_charger'),'device',(SELECT id FROM devices WHERE name = 'matts_usb_charger_bedroom'),1),
	 ((SELECT id FROM groups WHERE name = 'matts_usb_charger'),'device',(SELECT id FROM devices WHERE name = 'christmas_tree_usb'),1),
	 ((SELECT id FROM groups WHERE name = 'matts_usb_charger'),'device',(SELECT id FROM devices WHERE name = 'matts_usb_charger_bedroom'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen'),'group',(SELECT id FROM groups WHERE name = 'kitchen_main'),1),
	 ((SELECT id FROM groups WHERE name = 'kitchen'),'group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),1),
	 ((SELECT id FROM groups WHERE name = 'kids_room'),'device',(SELECT id FROM devices WHERE name = 'kids_room_1'),1),
	 ((SELECT id FROM groups WHERE name = 'kids_room'),'device',(SELECT id FROM devices WHERE name = 'kids_room_2'),1),
	 ((SELECT id FROM groups WHERE name = 'kids_room'),'device',(SELECT id FROM devices WHERE name = 'kids_room_3'),1);

INSERT INTO smart_home.aliases (model,model_id,alias,label,preferred,active) VALUES
	 ('device',(SELECT id FROM devices WHERE name = 'ship'),'fan','Fan',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'ship'),'bedroom_fan','Bedroom Fan',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'ship'),'master_bedroom_fan','Master Bedroom Fan',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'christmas_tree'),'computer','Computer',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'christmas_tree'),'plex','Plex',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'master_bathroom','Master Bathroom',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'master_bathroom_1','Master Bathroom 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'master_bathroom_2','Master Bathroom 2',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'bathroom','Bathroom',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'bathroom_1','Bathroom 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'bathroom_2','Bathroom 2',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),'bedroom','Bedroom',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_1'),'bedroom_1','Bedroom 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_2'),'bedroom_2','Bedroom 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_3'),'bedroom_3','Bedroom 3',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'master_bedroom_lamp','Master Bedroom Lamp',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'office'),'guest_room','Guest Room',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),'guest_room','Guest Room',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_1'),'guest_room_1','Guest Room 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_2'),'guest_room_2','Guest Room 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_3'),'guest_room_3','Guest Room 3',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'office'),'guest_bedroom','Guest Bedroom',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),'guest_bedroom','Guest Bedroom',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_1'),'guest_bedroom_1','Guest Bedroom 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_2'),'guest_bedroom_2','Guest Bedroom 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'office_3'),'guest_bedroom_3','Guest Bedroom 3',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'hallway'),'hall','Hall',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),'hallway','Hallway',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_1'),'hallway_1','Hallway 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_2'),'hallway_2','Hallway 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_3'),'hallway_3','Hallway 3',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_4'),'hallway_4','Hallway 4',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'vanity'),'master_vanity','Master Vanity',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),'vanity','Vanity',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'vanity_1'),'vanity_1','Vanity 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'vanity_2'),'vanity_2','Vanity 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'vanity_3'),'vanity_3','Vanity 3',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'vanity_4'),'vanity_4','Vanity 4',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'dining_room','Dining Room',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_1'),'dining_room_1','Dining Room 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_2'),'dining_room_2','Dining Room 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_3'),'dining_room_3','Dining Room 3',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_4'),'dining_room_4','Dining Room 4',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_5'),'dining_room_5','Dining Room 5',0,1),
	 ('group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'chandelier','Chandelier',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_1'),'chandelier_1','Chandelier 1',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_2'),'chandelier_2','Chandelier 2',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_3'),'chandelier_3','Chandelier 3',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_4'),'chandelier_4','Chandelier 4',0,1),
	 ('device',(SELECT id FROM devices WHERE name = 'dining_room_5'),'chandelier_5','Chandelier 5',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'kids_room'),'liams','Liam''s',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'kids_room'),'liams_room','Liam''s Room',0,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'kids_room'),'rowans_room','Rowan''s Room',0,1);

INSERT INTO smart_home.colors (name,label,value,display_value,active) VALUES
	 ('white','White','#ffffff','#ffffff',1),
	 ('softwhite','Soft White','#fefaf3','#fefaf3',1),
	 ('gray','Gray','#808080','#808080',1),
	 ('red','Red','#ff0000','#ff0000',1),
	 ('tomato','Tomato','#ff6347','#ff6347',1),
	 ('orange','Orange','#ffa500','#ffa500',1),
	 ('paleorange','Pale Orange','#ffdfbf','#ffdfbf',1),
	 ('yellow','Yellow','#ffff00','#ffff00',1),
	 ('paleyellow','Pale Yellow','#ffffe0','#ffffe0',1),
	 ('green','Green','#008000','#008000',1),
	 ('palegreen','Pale Green','#98fb98','#98fb98',1),
	 ('lime','Lime','#00ff00','#00ff00',1),
	 ('cyan','Cyan','#00ffff','#00ffff',1),
	 ('skyblue','Sky Blue','#87ceeb','#87ceeb',1),
	 ('paleblue','Pale Blue','#afddee','#afddee',1),
	 ('blue','Blue','#0000ff','#0000ff',1),
	 ('purple','Purple','#8800ff','#8800ff',1),
	 ('palepurple','Pale Purple','#e6e6fa','#e6e6fa',1),
	 ('magenta','Magenta','#ff00ff','#ff00ff',1),
	 ('pink','Pink','#ffc0ee','#ffc0ee',1),
	 ('hotpink','Hot Pink','#ff69b4','#ff69b4',1),
	 ('rose','ROSE','#f00060','#f00060',1),
	 ('redorange','Red Orange','#ff6201','#ff6201',1);

INSERT INTO smart_home.presets (model,model_id,name,label,active) VALUES
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'good_morning','Good Morning',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'nightlight','Nightlight',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'daytime','Daytime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'evening','Evening',1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'nightlight','Nightlight',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kids_room'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kids_room'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kids_room'),'bedtime','Bedtime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'dim','Dim',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'movie','Movie',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'bedtime','Bedtime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'movie','Movie',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'bedtime','Bedtime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),'movie','Movie',1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_1'),'nightlight','Nightlight',1),
	 ('device',(SELECT id FROM devices WHERE name = 'hall_3'),'nightlight','Nightlight',1),
	 ('group',(SELECT id FROM groups WHERE name = 'closet'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'closet'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'closet'),'bedtime','Bedtime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),'good_morning','Good Morning',1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'vanity_2'),'nightlight','Nightlight',1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),'movie','Movie',1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),'bedtime','Bedtime',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),'daytime','Daytime',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),'dim','Dim',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),'movie','Movie',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),'bedtime','Bedtime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'balcony'),'daytime','Daytime',1),
	 ('device',(SELECT id FROM devices WHERE name = 'balcony'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),'daytime','Daytime',1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),'bedtime','Bedtime',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),'evening','Evening',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'evening','Evening',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'balcony'),'halloween','Halloween',1);

INSERT INTO smart_home.preset_actions (preset_id,`action`,value,datatype,active) VALUES
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'daytime'),'temperature','56','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'good_morning'),'brightness','48','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'good_morning'),'temperature','56','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'evening'),'brightness','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'evening'),'temperature','45','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'bedtime'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'bedtime'),'temperature','56','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bathroom_1') AND name = 'nightlight'),'brightness','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bathroom_1') AND name = 'nightlight'),'color','redorange','string',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'daytime'),'temperature','65','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'evening'),'temperature','33','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'daytime'),'brightness','48','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'daytime'),'temperature','55','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'evening'),'temperature','37','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'bedtime'),'brightness','3','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'bedtime'),'temperature','23','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'nightlight'),'brightness','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'nightlight'),'color','redorange','string',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'daytime'),'temperature','39','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'evening'),'temperature','39','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'daytime'),'temperature','31','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'dim'),'brightness','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'dim'),'temperature','31','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'movie'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'daytime'),'temperature','31','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'evening'),'brightness','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'evening'),'temperature','31','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'movie'),'brightness','6','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'movie'),'temperature','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'daytime'),'temperature','50','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'evening'),'temperature','25','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'movie'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'hall_1') AND name = 'nightlight'),'brightness','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'hall_1') AND name = 'nightlight'),'color','redorange','string',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'hall_3') AND name = 'nightlight'),'brightness','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'hall_3') AND name = 'nightlight'),'color','redorange','string',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'daytime'),'brightness','100','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'daytime'),'temperature','65','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'evening'),'temperature','39','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'daytime'),'temperature','51','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'good_morning'),'brightness','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'good_morning'),'temperature','33','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'evening'),'brightness','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'evening'),'temperature','51','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'bedtime'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'bedtime'),'temperature','51','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'vanity_2') AND name = 'nightlight'),'brightness','1','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'vanity_2') AND name = 'nightlight'),'color','redorange','string',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'daytime'),'temperature','33','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'evening'),'brightness','6','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'evening'),'temperature','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'movie'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'daytime'),'temperature','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'dim'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'dim'),'temperature','24','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'movie'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'daytime'),'brightness','100','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'daytime'),'temperature','40','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'evening'),'brightness','12','number',1),
	 ((SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'evening'),'temperature','10','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'daytime'),'brightness','72','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'daytime'),'temperature','39','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'evening'),'brightness','6','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'evening'),'temperature','39','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'bedtime'),'off','1','boolean',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'evening'),'brightness','48','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'evening'),'temperature','30','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'evening'),'brightness','48','number',1),
	 ((SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'evening'),'temperature','30','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'balcony') AND name = 'halloween'),'brightness','100','number',1),
	 ((SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'balcony') AND name = 'halloween'),'color','ff2c00','string',1);

INSERT INTO smart_home.conditional_actions (model,model_id,preset_id,`action`,condition_type,`condition`,active) VALUES
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'bathroom'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bathroom') AND name = 'evening'),'on','time','22:00->sunrise',1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'bedroom'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'bedroom') AND name = 'evening'),'on','time','22:00->sunrise',0),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),(SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'daytime'),'on','time',NULL,1),
	 ('device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),(SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'bedroom_lamp') AND name = 'evening'),'on','time','22:00->sunrise',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kids_room'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'kids_room'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kids_room') AND name = 'evening'),'on','time','22:00->sunrise',1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_hanging') AND name = 'evening'),'on','time','22:00->sunrise',1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'hall'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'hall') AND name = 'evening'),'on','time','22:00->sunrise',0),
	 ('group',(SELECT id FROM groups WHERE name = 'closet'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'closet'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'closet') AND name = 'evening'),'on','time','22:00->sunrise',0),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'vanity'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'vanity') AND name = 'evening'),'on','time','22:00->sunrise',1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'living_room'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'living_room') AND name = 'evening'),'on','time','22:00->sunrise',0),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),(SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'daytime'),'on','time',NULL,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'balcony'),(SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'daytime'),'on','time',NULL,1),
	 ('room',(SELECT id FROM rooms WHERE name = 'balcony'),(SELECT id FROM presets WHERE model = 'device' AND model_id = (SELECT id FROM devices WHERE name = 'balcony') AND name = 'evening'),'on','time','22:00->sunrise',0),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'daytime'),'on','time',NULL,1),
	 ('group',(SELECT id FROM groups WHERE name = 'office'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'office') AND name = 'evening'),'on','time','19:00->sunrise',1),
	 ('room',(SELECT id FROM rooms WHERE name = 'dining_room'),(SELECT id FROM presets WHERE model = 'room' AND model_id = (SELECT id FROM rooms WHERE name = 'dining_room') AND name = 'dim'),'on','time','22:00->sunrise',0),
	 ('group',(SELECT id FROM groups WHERE name = 'kitchen_main'),(SELECT id FROM presets WHERE model = 'group' AND model_id = (SELECT id FROM groups WHERE name = 'kitchen_main') AND name = 'dim'),'on','time','22:00->sunrise',1);

INSERT INTO smart_home.linked_devices (source_device_id,target_model,target_model_id,name,label,event,`action`,value,datatype,active) VALUES
	 ((SELECT id FROM devices WHERE name = 'office_light_switch'),'group',(SELECT id FROM groups WHERE name = 'office'),'office_light_switch_off','Office Light Switch OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'office_light_switch'),'group',(SELECT id FROM groups WHERE name = 'office'),'office_light_switch_on','Office Light Switch ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'office_light_switch'),'group',(SELECT id FROM groups WHERE name = 'office'),'office_light_switch_dimmer','Office Light Switch DIMMER','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'office_1'),'device',(SELECT id FROM devices WHERE name = 'office_light_switch'),'office_off','Office OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'office_1'),'device',(SELECT id FROM devices WHERE name = 'office_light_switch'),'office_on','Office ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'office_1'),'device',(SELECT id FROM devices WHERE name = 'office_light_switch'),'office_brightness','Office BRIGHTNESS','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kitchen'),'kitchen_light_switch_off','Kitchen Light Switch OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kitchen'),'kitchen_light_switch_on','Kitchen Light Switch ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kitchen'),'kitchen_light_switch_dimmer','Kitchen Light Switch DIMMER','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_1'),'device',(SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'kitchen_off','Kitchen OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_1'),'device',(SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'kitchen_on','Kitchen ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kitchen_1'),'device',(SELECT id FROM devices WHERE name = 'kitchen_light_switch'),'kitchen_brightness','Kitchen BRIGHTNESS','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_light_switch'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'vanity_light_switch_off','Vanity Light Switch OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_light_switch'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'vanity_light_switch_on','Vanity Light Switch ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_light_switch'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'vanity_light_switch_dimmer','Vanity Light Switch DIMMER','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_1'),'device',(SELECT id FROM devices WHERE name = 'vanity_light_switch'),'vanity_off','Vanity OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_1'),'device',(SELECT id FROM devices WHERE name = 'vanity_light_switch'),'vanity_on','Vanity ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'vanity_1'),'device',(SELECT id FROM devices WHERE name = 'vanity_light_switch'),'vanity_brightness','Vanity BRIGHTNESS','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'bathroom_light_switch_off','Bathroom Light Switch OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'bathroom_light_switch_on','Bathroom Light Switch ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'bathroom_light_switch_dimmer','Bathroom Light Switch DIMMER','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_1'),'device',(SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'bathroom_off','Bathroom OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_1'),'device',(SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'bathroom_on','Bathroom ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'bathroom_1'),'device',(SELECT id FROM devices WHERE name = 'bathroom_light_switch'),'bathroom_brightness','Bathroom BRIGHTNESS','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'kids_room_light_switch_off','Kids'' Room Light Switch OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'bathroom_light_switch_on','Kids'' Room Light Switch ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'kids_room_light_switch_dimmer','Kids'' Room Light Switch DIMMER','brightness','brightness','mirror','number',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_1'),'device',(SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'kids_room_off','Kids'' Room OFF','off','off','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_1'),'device',(SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'kids_room_on','Kids'' Room ON','on','on','true','boolean',1),
	 ((SELECT id FROM devices WHERE name = 'kids_room_1'),'device',(SELECT id FROM devices WHERE name = 'kids_room_light_switch'),'kids_room_brightness','Kids'' Room BRIGHTNESS','brightness','brightness','mirror','number',1);

INSERT INTO smart_home.scenes (name,label,`order`,active) VALUES
	 ('daytime_all','Daytime All',100,1),
	 ('good_morning','Good Morning',200,1),
	 ('evening_all','Evening All',300,1),
	 ('evening','Evening',400,1),
	 ('movie','Movie',500,1),
	 ('bedtime','Bedtime',600,1),
	 ('nightlight','Nightlight',700,1);

INSERT INTO smart_home.scene_actions (scene_id,model,model_id,`action`,value,datatype,active) VALUES
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'living_room'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'closet'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'hall'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'kitchen'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'bedroom'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'good_morning'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'preset','good_morning','string',1),
	 ((SELECT id FROM scenes WHERE name = 'good_morning'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'preset','good_morning','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'living_room'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'closet'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'hall'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'bedroom'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'living_room'),'off','1','boolean',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'hall'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'movie'),'group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'preset','movie','string',1),
	 ((SELECT id FROM scenes WHERE name = 'movie'),'group',(SELECT id FROM groups WHERE name = 'living_room'),'off','1','boolean',1),
	 ((SELECT id FROM scenes WHERE name = 'movie'),'group',(SELECT id FROM groups WHERE name = 'hall'),'preset','movie','string',1),
	 ((SELECT id FROM scenes WHERE name = 'movie'),'group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'preset','movie','string',1),
	 ((SELECT id FROM scenes WHERE name = 'movie'),'group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'preset','movie','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'dining_chandelier'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'living_room'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'vanity'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'closet'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'hall'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'kitchen_main'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'kids_room'),'preset','bedtime','string',0),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'bedroom'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'bathroom'),'preset','bedtime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'nightlight'),'device',(SELECT id FROM devices WHERE name = 'hall_1'),'preset','nightlight','string',1),
	 ((SELECT id FROM scenes WHERE name = 'nightlight'),'device',(SELECT id FROM devices WHERE name = 'hall_3'),'preset','nightlight','string',1),
	 ((SELECT id FROM scenes WHERE name = 'nightlight'),'device',(SELECT id FROM devices WHERE name = 'bedroom_lamp'),'off','1','boolean',1),
	 ((SELECT id FROM scenes WHERE name = 'nightlight'),'device',(SELECT id FROM devices WHERE name = 'bathroom_1'),'preset','nightlight','string',1),
	 ((SELECT id FROM scenes WHERE name = 'nightlight'),'device',(SELECT id FROM devices WHERE name = 'vanity_2'),'preset','nightlight','string',1),
	 ((SELECT id FROM scenes WHERE name = 'daytime_all'),'device',(SELECT id FROM devices WHERE name = 'balcony'),'preset','daytime','string',1),
	 ((SELECT id FROM scenes WHERE name = 'evening_all'),'device',(SELECT id FROM devices WHERE name = 'balcony'),'preset','evening','string',1),
	 ((SELECT id FROM scenes WHERE name = 'bedtime'),'group',(SELECT id FROM groups WHERE name = 'kitchen_hanging'),'preset','movie','string',1);
